name: Complete-DevSecOps-Pipeline-With-Blocking

on:
  workflow_dispatch:

jobs:

  Secrets:
 
    runs-on: ubuntu-latest

    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~

      - name: Dumping Source Code
        uses: actions/checkout@v3

# ~~~~~~~~~~~~~~~~~~~ Secret Scanning ~~~~~~~~~~~~~~~~~~~

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


  SCA:
 
    runs-on: ubuntu-latest

    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~

      - name: Dumping Source Code
        uses: actions/checkout@v3

#~~~~~~~~~~ Installing Dependencies ~~~~~~~~~~

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm install

#~~~~~~~~~~ Running Dependency Scan ~~~~~~~~~~
        
      - name: Dependency Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          type: "credscan,depscan"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

#~~~~~~~~~~ Uploading Results ~~~~~~~~~~

      - name: Uploading Scan Reports 
        uses: actions/upload-artifact@v1
        with:
          name: Dependency-and-Secret-Reports
          path: reports


  SAST:
  
    runs-on: ubuntu-latest
    
    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~
    
    - name: Checkout the code
      uses: actions/checkout@v3

# ~~~~~~~~~~~~~~~~~~~ Running SAST Scan ~~~~~~~~~~~~~~~~~~~
    
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'

  Container-Scanning:
    
    needs: SAST
    runs-on: ubuntu-latest

    steps:

# ~~~~~~~~~~~~~~~~~~~ Dumping Code ~~~~~~~~~~~~~~~~~~~

      - name: Dumping Source Code
        uses: actions/checkout@v3

# ~~~~~~~~~~~~~~~~~~~ Secret Scanning ~~~~~~~~~~~~~~~~~~~

      - name: Build an image from Dockerfile
        run: |
          docker build -t vulnerable-nodejs-app:v1 .
          
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-nodejs-app:v1'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
